# Generated by Django 5.1.2 on 2024-10-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cartitem_cart_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
