# Generated by Django 5.1.2 on 2024-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_settlementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement_request_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
    ]
